### ISSUE TITLE
Project Requirements Checklist

### ISSUE THREAD

**Issue by britt-young** [britt-young/get_your_list_together#12]
- [x]  Use Node.js and Express.js to create a RESTful API.

- [x]  Use Handlebars.js as the templating engine.

- [x]  Use MySQL and the Sequelize ORM for the database.

- [x]  Have both GET and POST routes for retrieving and adding new data.

- [ ]  Be deployed using Heroku (with data).

- [x]  Use at least one new library, package, or technology that we haven’t discussed.

- [x] Have a polished UI.

- [x]  Be responsive.

- [ ]  Be interactive (i.e., accept and respond to user input).

- [ ]  Have a folder structure that meets the MVC paradigm.

- [ ]  Include authentication (express-session and cookies).

- [x]  Protect API keys and sensitive information with environment variables.

- [x]  Have a clean repository that meets quality coding standards (file structure, naming conventions, follows best practices for class/id naming conventions, indentation, quality comments, etc.).

- [ ]  Have a quality README (with unique name, description, technologies used, screenshot, and link to deployed application).
